name: Build .deb (Theos)

on:
  push:
    paths:
      - '**.xm'
      - '**.m'
      - '**.mm'
      - '**.h'
      - 'tweak/**'
      - 'prefs/**'
      - 'debian/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make perl python3 fakeroot ldid dpkg-dev ca-certificates

      - name: Setup Theos (Linux toolchain + SDKs)
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          git clone --depth=1 https://github.com/theos/toolchain-linux.git ~/theos/toolchain/linux/iphone
          git clone --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build .deb (rootless)
        env:
          THEOS: /home/runner/theos
        working-directory: tweak/W2Like
        run: |
          make package
          ls -lah packages

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: w2like-deb
          path: tweak/W2Like/packages/*.deb
