name: Rebuild APT index

on:
  workflow_dispatch:

# ⬅️ allow the workflow to push back to the repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # optional, but nice to have

      - name: Build APT index (Packages/Packages.gz)
        run: bash index.sh

      - name: Commit & push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          # Only commit if there are changes
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update APT index"

            # Push using the token in the URL (avoids interactive auth)
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" HEAD:${BRANCH}
          else
            echo "No changes to commit."
          fi
